FROM node:24-alpine

RUN corepack enable pnpm
RUN apk add --no-cache git openssh-client bash curl

WORKDIR /app

# ✅ Déclare les arguments build-time
ARG GITHUB_TOKEN
ARG NODE_ENV
ARG PORT
ARG NUXT_PUBLIC_INDEXABLE
ARG NUXT_PUBLIC_URL
ARG NUXT_MAILER_HOST
ARG NUXT_MAILER_PORT
ARG NUXT_MAILER_SECURE
ARG NUXT_MAILER_USER
ARG NUXT_MAILER_PASS
ARG NUXT_MAILER_NAME
ARG NODE_ENV


ENV GITHUB_TOKEN=${GITHUB_TOKEN}
ENV NODE_ENV=${NODE_ENV}
ENV PORT=${PORT}
ENV NUXT_PUBLIC_INDEXABLE=${NUXT_PUBLIC_INDEXABLE}
ENV NUXT_PUBLIC_URL=${NUXT_PUBLIC_URL}
ENV NUXT_MAILER_HOST=${NUXT_MAILER_HOST}
ENV NUXT_MAILER_PORT=${NUXT_MAILER_PORT}
ENV NUXT_MAILER_SECURE=${NUXT_MAILER_SECURE}
ENV NUXT_MAILER_USER=${NUXT_MAILER_USER}
ENV NUXT_MAILER_PASS=${NUXT_MAILER_PASS}
ENV NUXT_MAILER_NAME=${NUXT_MAILER_NAME}
ENV NODE_ENV=${NODE_ENV}

ADD . .
# ADD package.json .npmrc .pnpmfile.cjs ./
RUN pnpm i --prod
RUN pnpm build

EXPOSE ${PORT}

CMD ["node", "./server.mjs"]


