name: Deployment

on:
  push:
    branches:
      - main
      - netlify

jobs:
  deploy:
    runs-on: ovh-b2-7-uk1 # ton runner self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Create .env file
        env:
          DOT_ENV: ${{ secrets.DOT_ENV }}
        run: |
          echo "$DOT_ENV" > .env
          echo "$DOT_ENV" > env
          ls

      - name: Pull latest containers and restart stack
        run: |
          docker compose down
          docker compose pull
          docker compose up -d --build
