name: Deployment

on:
  push:
    branches:
      - main
      - develop

jobs:
  set-env:
    runs-on: self-hosted
    outputs:
      env: ${{ steps.define-env.outputs.env }}
      envs_dir: ${{ steps.define-env.outputs.envs_dir }}
      deploy_dir: ${{ steps.define-env.outputs.deploy_dir }}

    steps:
      - name: Define environment from branch
        id: define-env
        run: |
          BRANCH="${GITHUB_REF_NAME}"
          case "$BRANCH" in
            main) ENV="production" ;;
            develop) ENV="development" ;;
            *) echo "❌ Branche non déployable : $BRANCH" && exit 1 ;;
          esac

          echo "ENV=$ENV" >> $GITHUB_ENV
          echo "env=$ENV" >> $GITHUB_OUTPUT

          ENVS_DIR="$HOME/prod/site/$ENV.env"
          echo "envs_dir=$ENVS_DIR" >> $GITHUB_OUTPUT

          DEPLOY_DIR="$HOME/prod/site/$ENV"
          echo "deploy_dir=$DEPLOY_DIR" >> $GITHUB_OUTPUT

  build:
    runs-on: self-hosted
    needs: set-env
    env:
      ENV: ${{ needs.set-env.outputs.env }}
      ENVS_DIR: ${{ needs.set-env.outputs.envs_dir }}
      DEPLOY_DIR: ${{ needs.set-env.outputs.deploy_dir }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Copy project to deploy dir
        run: |
          mkdir -p $DEPLOY_DIR
          cp -r ./* $DEPLOY_DIR

      - name: Install corepack
        run: npm i -g --force corepack@latest && corepack enable pnpm

      - name: Install dependencies
        run: |
          cd $DEPLOY_DIR
          rm pnpm-lock.yaml
          pnpm install --frozen-lockfile

      - name: Build project
        run: |
          cd $DEPLOY_DIR
          pnpm build

      # - name: Copy files to deploy dir
      #   run: |
      #     mkdir -p "$DEPLOY_DIR"
      #     cp -r ./* "$DEPLOY_DIR"

      # - name: Copy and install build
      #   run: |
      #     mkdir -p $DEPLOY_DIR

      #     cp .pnpmfile.cjs build
      #     cp build/* $DEPLOY_DIR

      #     cd $DEPLOY_DIR
      #     pnpm install --prod --frozen-lockfile

  # deploy:
  #   runs-on: self-hosted
  #   needs:  needs: [set-env, build]

  # env:
  #   ENV: ${{ needs.set-env.outputs.env }}
  #   ENVS_DIR: ${{ needs.set-env.outputs.envs_dir }}
  #   DEPLOY_DIR: ${{ needs.set-env.outputs.deploy_dir }}

  #   steps:
  #     - name: Create service
  #       run: |
  #         SERVICE_NAME="$ENV-tarico-site.service"
  #         SERVICE_PATH="/etc/systemd/system/$SERVICE_NAME"

  #         common_unit_header="[Unit]
  #         Type=simple
  #         Description=$ENV-tarico-site
  #         After=network-online.target
  #         Wants=network-online.target

  #         [Service]
  #         WorkingDirectory="$DEPLOY_DIR"
  #         ExecStart="$WHICH_NODE" run.js
  #         Restart=always
  #         RestartSec=5
  #         KillMode=process
  #         TimeoutStopSec=15s"

  #         common_unit_footer="
  #         [Install]
  #         WantedBy=multi-user.target"

  #         env_file_content=""

  #         while IFS= read -r line; do
  #           [[ -z "$line" || "$line" =~ ^# ]] && continue
  #           env_file_content+="Environment=$line\n"
  #         done < "$ENVS_DIR"

  #         CONFIG_FILE="./.config.json"
  #         port=$(jq -r ".port.${ENV}" "$CONFIG_FILE")
  #         env_file_content+="Environment=PORT=$port\n"

  #         service="${common_unit_header}\n${env_file_content}\n${common_unit_footer}"

  #         printf "$service" | sudo tee "$SERVICE_PATH" > /dev/null

  #         sudo systemctl daemon-reload
  #         sudo systemctl restart "$SERVICE_NAME"

  #     - name: Nginx configuration
  #       run: |
  #         #!/bin/bash

  #         # Templates multilignes
  #         TEMPLATE_HTTP=$(cat <<'EOF'
  #         server {
  #           listen 80;
  #           server_name $URL www.$URL;

  #           location /.well-known/acme-challenge/ {
  #             root /var/www/letsencrypt;
  #           }

  #           location / {
  #             return 301 https://$host$request_uri;
  #           }
  #         }
  #         EOF
  #         )

  #         TEMPLATE_HTTPS=$(cat <<'EOF'
  #         server {
  #           listen 443 ssl http2;
  #           server_name $URL www.$URL;

  #           ssl_certificate /etc/letsencrypt/live/$URL/fullchain.pem;
  #           ssl_certificate_key /etc/letsencrypt/live/$URL/privkey.pem;

  #           ssl_protocols TLSv1.2 TLSv1.3;
  #           ssl_ciphers HIGH:!aNULL:!MD5;
  #           ssl_prefer_server_ciphers on;

  #           ssl_session_cache shared:SSL:10m;
  #           ssl_session_timeout 1h;
  #           ssl_session_tickets off;

  #           location /.well-known/acme-challenge/ {
  #             root /var/www/letsencrypt;
  #           }

  #           location / {
  #             proxy_pass http://localhost:$PORT;
  #             proxy_http_version 1.1;
  #             proxy_set_header Host $host;
  #             proxy_set_header X-Real-IP $remote_addr;
  #             proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
  #             proxy_set_header X-Forwarded-Proto $scheme;
  #             proxy_set_header Upgrade $http_upgrade;
  #             proxy_set_header Connection 'upgrade';
  #             proxy_cache_bypass $http_upgrade;
  #           }

  #           error_page 502 503 504 /50x.html;
  #           location = /50x.html {
  #             root /var/www/html/errors;
  #             internal;
  #           }
  #         }
  #         EOF
  #         )

  #         # Lire le fichier .env et charger dans des variables locales
  #         while IFS='=' read -r key value; do
  #             # Ignorer les lignes vides ou les commentaires
  #             if [[ -n "$key" && ! "$key" =~ ^# ]]; then
  #                 # Supprimer d'éventuels guillemets
  #                 value="${value%\"}"
  #                 value="${value#\"}"

  #                 # Créer une variable simple
  #                 declare "_$key=$value"
  #             fi
  #         done < "$ENVS_DIR"

  #         port="_$PORT"
  #         domain="_$DOMAIN"

  #         restart_nginx() {
  #             sudo systemctl restart nginx
  #             echo "Redémarrage de NGINX..."

  #             # Attendre max 10 secondes
  #             for i in {1..20}; do
  #                 if systemctl is-active --quiet nginx; then
  #                     echo "NGINX est actif ✅"
  #                     break
  #                 fi
  #                 sleep 0.5
  #             done

  #             # Vérification finale
  #             if ! systemctl is-active --quiet nginx; then
  #                 echo "❌ Échec : NGINX ne redémarre pas."
  #                 exit 1
  #             fi
  #         }

  #         if [[ "$domain" != null && "$port" != null ]];then
  #             EMAIL="contact@tarico.io"
  #             CONF_PATH="/etc/nginx/sites-available/${domain}.conf"
  #             ENABLED_PATH="/etc/nginx/sites-enabled/${domain}.conf"

  #             # Générer le fichier de configuration Nginx
  #             echo "$TEMPLATE_HTTP" | URL="$domain" PORT="$port" envsubst '${URL} ${PORT}' | sudo tee "$CONF_PATH" >/dev/null

  #             # Créer le lien symbolique s'il n'existe pas
  #             if [ ! -f "$ENABLED_PATH" ]; then
  #                 sudo ln -s "$CONF_PATH" "$ENABLED_PATH"
  #             fi

  #             restart_nginx

  #             # Générer SSL avec Certbot
  #             echo "🔐 Obtention du certificat SSL pour $domain ..."
  #             sudo ~/certbot-venv/bin/certbot  certonly \
  #                 --webroot -w /var/www/letsencrypt \
  #                 -d "$domain" -d "www.$domain" \
  #                 --email "$EMAIL" \
  #                 --non-interactive --agree-tos -v --expand

  #             echo "$TEMPLATE_HTTPS" | URL="$domain" PORT="$port" envsubst '${URL} ${PORT}' | sudo tee -a "$CONF_PATH" >/dev/null

  #             restart_nginx
  #             echo "✅ nginx configuré pour $domain"
  #         fi
